### ISSUE TITLE
Integrate imebra into existing code

### ISSUE THREAD

**Issue by Reese-D** [GVSU-CIS467-Team-Microsoft/Project#12]
Imebra works for reading pixel data out of files, but now we need to integrate this functionality into the existing neural network, so that a set of images can be given to the ANN to use.

**Comment by RonPatrick1** [comment]
I did this already on 2/19/17.  I compiled Imebra library downloaded from here and Imebra, included the header and integrated the compile command-lines into the Makefile.  So the example code Reese provided can now be run directly in pConcept2.cpp (and consequently pConcept2.cu)
